apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  # FIXME: Replace here with your piped ID.
  pipedID: d63316fe-537e-42ca-a435-ade338129b34
  # Base64 encoded string of the piped private key.
  # FIXME: Replace here with your piped base64 key.
  pipedKeyData: aWZudDF1ZW0yaXI4M2VtdDEwZWM2dnJhYW1vbDdna2J2bW9qNTd3Y2s2ajZva2lnbGg=
  # Write in a format like "host:443" because the communication is done via gRPC.
  # FIXME: Replace here with your piped address if you connect Piped to a control plane that does not run locally.
  apiAddress: localhost:8080
  repositories:
  - repoId: CD
    remote: https://github.com/Initify-v1/CD.git
    branch: main
  syncInterval: 1m
  plugin:
    - name: k8s_plugin
      port: 8081
      deployTargets:
        - name: dev
          labels: 
            env: dev
          config: # depends on plugins
            masterURL: http://cluster-dev
            kubeConfigPath: /Users/niladri/.kube/config
