apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  # FIXME: Replace here with your piped ID.
  pipedID: ecaa1758-ed4c-4aad-9b9b-6eb1b8bc13c3
  # Base64 encoded string of the piped private key.
  # FIXME: Replace here with your piped base64 key.
  pipedKeyData: dTRhbnJrMXllcHh6eWhlMHFwMHY3a2c1Ym52aHlpd3ptcXd5NW1pd2JuM2t2MTU0anQ=
  # Write in a format like "host:443" because the communication is done via gRPC.
  # FIXME: Replace here with your piped address if you connect Piped to a control plane that does not run locally.
  apiAddress: localhost:8080
  repositories:
  - repoId: CD3
    remote: https://github.com/Initify-v1/CD3.git
    branch: main
  syncInterval: 1m
  plugins:
      - name: kubernetes
        type: kubernetes
        port: 7003 # FIXME: any unused port
        url: file:///Users/niladri/.piped/plugins/kubernetes # It's OK using any value for now because it's a dummy. We will implement it later.
        deployTargets: # This field is alternative for platform providers
        - name: kubernetes-dev
          labels:
            kind: KUBERNETES
          config:
            masterURL: https://127.0.0.1:50950 # FIXME: shown by kubectl cluster-info
            # FIXME: Replace here with your kubeconfig absolute file path.
            kubeConfigPath: /Users/niladri/.kube/config
